# Generated by Django 3.1.3 on 2020-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('summary', models.TextField(help_text='설명을 적으세요', max_length=1000)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('acount', models.CharField(max_length=1)),
            ],
        ),
    ]
