# Generated by Django 3.1.3 on 2020-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realproject', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=500)),
            ],
        ),
    ]
