# Generated by Django 3.1.3 on 2020-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realproject', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
